include=~/.config/fuzzel/catppuccin-fuzzel/themes/catppuccin-mocha/red.ini
include=~/.config/fuzzel/catppuccin-fuzzel/themes/catppuccin-mocha/red.ini

[main]
font=FiraCode Nerd Font:size=14
terminal=alacritty
dpi-aware=no

width=45
lines=8
horizontal-pad=20
vertical-pad=20
inner-pad=10

prompt="   " 

show-actions=no
layer=overlay

[border]
radius=12
width=2

[colors]
background=1e1e2e80
# Matches the background so the counter becomes invisible for a cleaner look
counter=1e1e2eff 
border=f38ba8ff
