#! /bin/sh

# picom --config $HOME/.config/picom.conf --experimental-backends &

# openrgb --server &
# openrgb -p default &
picom --config $HOME/.config/picom.conf &
$HOME/.config/polybar/scripts/map_mono_mic.sh &
gnome-keyring-daemon --start &
fcitx5 -d &
# setxkbmap us -variant dpe
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2 -d 2 4 6 8 10
bspc monitor HDMI-0 -d 1 3 5 7 9

bspc config border_width         2
# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color2"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"
bspc config -m DP-2 window_gap          15
bspc config -m DP-2 top_padding         55
bspc config -m DP-2 bottom_padding      55
bspc config -m DP-2 left_padding        15
bspc config -m DP-2 right_padding       15

bspc config -m HDMI-0  window_gap          15
bspc config -m HDMI-0  top_padding         55
bspc config -m HDMI-0  bottom_padding      0
bspc config -m HDMI-0  left_padding        0
bspc config -m HDMI-0  right_padding       0

bspc config split_ratio         0.50
bspc config borderless_monocle  false
bspc config gapless_monocle     false
bspc config automatic_scheme    alternate

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
# bspc rule -a Steam desktop=^2 state=floating manage=on layer=normal focus=off
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a polybar state=sticky
$HOME/.config/polybar/launch.sh &
source ~/.fehbg &
