# preload = ~/Pictures/red_moon/red_moon-latte.jpg
preload = ~/Pictures/red_moon/red_moon-latte.jpg
# wallpaper = ,~/Pictures/red_moon/red_moon-latte.jpg
wallpaper = , ~/Pictures/red_moon/red_moon-latte.jpg
