add_newline = false
format = """
$username\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$status\
$linebreak
$directory\
$character"""
[character]
success_symbol = ">"
error_symbol = "[X](red)"
vicmd_symbol = "<"
[directory]
read_only = "  "
read_only_style = "red"
[package]
symbol = " "
[username]
format = "[$user]($style) "
disabled = false
show_always = true
[git_branch]
symbol = ""
