
# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=eDP-1, preferred, 0x0, 1
# monitor=DP-4, preferred, auto, 1, mirror, eDP-1
monitor=,preferred,auto,auto
# trigger when the switch is turning off
# bindl = , switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1, 1920x1080@60, 0x0, 1"
# trigger when the switch is turning on
# bindl = , switch:on:Lid Switch,exec,hyprctl keyword monitor "eDP-1, disable"
