
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrulev2=noblur,class:^()$,title:^()$


# games for tearing add the immediate rule
windowrule = immediate, class:^(cs2)$

# Float Windows
windowrule=float,title:^(Open File)$
windowrule=float,title:^(Select a File)$
windowrule=float,title:^(Choose a file)$
windowrule=float,title:^(Save As)$
windowrule=float,title:^(Save File)$
windowrule=float,title:^(branchdialog)$
windowrule=float,title:^(pinentry-gtk-2)$
windowrule=float,title:^(Confirm to replace files)$
windowrule=float,title:^(File Operation Progress)$
windowrule=float,class:^(pavucontrol|blueman-manager|nm-connection-editor)$

# Center and Resize Windows
windowrule=size 800 600,title:^(Open File)$
windowrule=size 800 600,title:^(Select a File)$
windowrule=size 800 600,title:^(Choose a file)$
windowrule=size 800 600,title:^(Save As)$
windowrule=size 800 600,title:^(Save File)$
windowrule=size 800 600,title:^(branchdialog)$
windowrule=size 800 600,title:^(pinentry-gtk-2)$
windowrule=size 800 600,title:^(Confirm to replace files)$
windowrule=size 800 600,title:^(File Operation Progress)$
windowrule=size 800 600,class:^(pavucontrol|blueman-manager|nm-connection-editor)$
windowrule=center,title:^(Open File)$
windowrule=center,title:^(Select a File)$
windowrule=center,title:^(Choose a file)$
windowrule=center,title:^(Save As)$
windowrule=center,title:^(Save File)$
windowrule=center,title:^(branchdialog)$
windowrule=center,title:^(pinentry-gtk-2)$
windowrule=center,title:^(Confirm to replace files)$
windowrule=center,title:^(File Operation Progress)$
windowrule=center,class:^(pavucontrol|blueman-manager|nm-connection-editor)$

# Workspace Rules
windowrule=workspace 1,class:^(firefox)$
windowrule=workspace 2,class:^(kitty)$
windowrule=workspace 3,class:^(Code)$
windowrule=workspace 4,class:^(steam)$
windowrule=workspace 5,class:^(discord)$
