#!/bin/bash

if (($# != 2)); then
    printf "Invalid arguments, try:\n\ncorona -ls [amount]\ncorona -c [country]\n"
    exit 2
fi

if [ "$1" == "-ls" ]; then
    curl -s https://corona-stats.online?top=$2
    exit 0
elif [ "$1" == "-c" ]; then
    curl -s https://corona-stats.online/$2
else
    printf "Unknown option: $1"
fi
