#!/bin/bash

lock() {
    i3lock
}

choices="Lock\nSuspend\nLogout\nPoweroff\nReboot"
chosen=$(echo -e $choices | rofi -dmenu -i -p "Power Menu" -theme ~/.cache/colorer/rofi.rasi)
echo "$chosen"

case "$chosen" in
        Lock) lock ;;
        Suspend) lock && systemctl suspend ;;
		Logout) i3-msg exit ;;
		Poweroff) systemctl poweroff ;;
		Reboot) systemctl reboot ;;
esac
