#!/bin/bash

if (($# != 1)); then
    printf "Provide a path with images\n"
    exit 2
fi

if [ -d "$1" ]; then

    while true;
    do
        for f in "$1"*;
        do
            xwallpaper --zoom "$f"
            sleep 6000s
        done
    done
else
    printf "Invalid directory: $1\n"
    exit 2
fi
